---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcements-deployment
  labels:
    app: announcements
spec:
  replicas: 3
  selector:
    matchLabels:
      app: announcements
  template:
    metadata:
      labels:
        app: announcements
    spec:
      containers:
      - name: announcements-api
        image: itselavia/announcements
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: announcements-service
spec:
  selector:
    app: announcements
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
