---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  labels:
    app: course
spec:
  replicas: 3
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - name: course-api
        image: nirbhayk/courses_ms:7f05dd9
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "10.0.3.127:27017"
        - name: DATABASE
          value: "testdb"
        - name: COLLECTION
          value: "courses"
        - name: KAFKA_SERVER
          value: "54.91.195.100:9092"
        - name: COURSE_CLICK_TOPIC
          value: "search-topic"
        - name: ENROLLMENT_TOPIC
          value: "ENROLLMENT_TOPIC"
---

apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
