---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-deployment
  labels:
    app: course
spec:
  replicas: 3
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - name: course-api
        image: nirbhayk/courses_ms:VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
