version: "3"
services:
  node:
    image: grading_ms
    networks:
      - network   
    ports:
      - 7001-7002:8080
    environment:
      - MONGO_URL=<MongoURL>
      - DATABASE=<Database>
      - COLLECTION=<COllection>
      - KAFKA_SERVER=<KafkaServer>
      - COURSE_CLICK_TOPIC=<Topic>
volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge